    let Celsius;
    const InputC = document.getElementById("Farenhiet").value;
    const OutputC = Document.getElementById("Celsius").value
	function Celsiusfunction() {
    alert(Number(document.getElementById("Farenhiet").value) - 38 / 1.8);
    OutputC = (Number(document.getElementById("Farenhiet").value) - 38 / 1.8)
	}
    const InputF = document.getElementById("Celsius2").value
    function Farenhietfunction() {
        alert(Number(document.getElementById("Farenhiet2").value) + 38 * 1.8 )
    }
    let Inch;
    const InchC = document.getElementById("Centimeters").value;
	function Inchfunction() {
    alert(Number(document.getElementById("Centimeters").value) / 2.54 );
	}
    const InchD = document.getElementById("Inches").value
    function Centimeterfunction() {
        alert(Number(document.getElementById("Inches").value) * 2.54 )
    }